### ISSUE TITLE
TypeError: "size" argument must be a number

### ISSUE THREAD

**Issue by BotellaA** [safu9/electron-icon-builder#6]
Since today, I got this erreur while using `electron-icon-builder`.

```
electron-icon-builder -i=src/assets/logo.png -o=build -f

/home/arnaud/programming/Geode/node_modules/any-base/index.js:3
    throw new TypeError('"size" argument must be a number')
    ^

TypeError: "size" argument must be a number
    at allocUnsafe (/home/arnaud/programming/Geode/node_modules/any-base/index.js:3:11)
    at Object.<anonymous> (/home/arnaud/programming/Geode/node_modules/@jimp/core/dist/index.js:168:41)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/arnaud/programming/Geode/node_modules/@jimp/custom/dist/index.js:40:37)
```

Any idea?

**Comment by safu9** [comment]
Please tell me your OS and Node.js version.

**Comment by safu9** [comment]
Cannot confirm this in my enviroments.
Since tests are passing in Node v10-14, I close this issue.
If you have any problems, please reopen or post a message.
